/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author MIGUEL TULANDE
 */
public class CambiarContraseña extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public CambiarContraseña() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbRegistrar = new javax.swing.JLabel();
        btnCambiarContraseñaConfirmar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jCheckBoxCambiarContraseña2 = new javax.swing.JCheckBox();
        jCheckBoxCambiarContraseña1 = new javax.swing.JCheckBox();
        jTextCambiarContraseñaConfirmar2 = new javax.swing.JTextField();
        jTextCambiarContraseñaConfirmar1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbRegistrar.setBackground(new java.awt.Color(0, 0, 0));
        lbRegistrar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        lbRegistrar.setText("CAMBIAR CONTRASEÑA");
        jPanel1.add(lbRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        btnCambiarContraseñaConfirmar.setBackground(new java.awt.Color(0, 153, 255));
        btnCambiarContraseñaConfirmar.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        btnCambiarContraseñaConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiarContraseñaConfirmar.setText("CONFIRMAR");
        btnCambiarContraseñaConfirmar.setBorder(null);
        jPanel1.add(btnCambiarContraseñaConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 170, 30));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 470));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 190, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, -1, 360));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 190, 10));

        jCheckBoxCambiarContraseña2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCambiarContraseña2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxCambiarContraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, -1, -1));

        jCheckBoxCambiarContraseña1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCambiarContraseña1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxCambiarContraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        jTextCambiarContraseñaConfirmar2.setBackground(new java.awt.Color(204, 204, 204));
        jTextCambiarContraseñaConfirmar2.setFont(new java.awt.Font("Bookshelf Symbol 7", 0, 12)); // NOI18N
        jTextCambiarContraseñaConfirmar2.setForeground(new java.awt.Color(0, 0, 0));
        jTextCambiarContraseñaConfirmar2.setText("Contraseña");
        jTextCambiarContraseñaConfirmar2.setBorder(null);
        jPanel1.add(jTextCambiarContraseñaConfirmar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 190, -1));

        jTextCambiarContraseñaConfirmar1.setBackground(new java.awt.Color(204, 204, 204));
        jTextCambiarContraseñaConfirmar1.setFont(new java.awt.Font("Bookshelf Symbol 7", 0, 12)); // NOI18N
        jTextCambiarContraseñaConfirmar1.setForeground(new java.awt.Color(0, 0, 0));
        jTextCambiarContraseñaConfirmar1.setText("Contraseña");
        jTextCambiarContraseñaConfirmar1.setBorder(null);
        jPanel1.add(jTextCambiarContraseñaConfirmar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxCambiarContraseña2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCambiarContraseña2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxCambiarContraseña2ActionPerformed

    private void jCheckBoxCambiarContraseña1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCambiarContraseña1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxCambiarContraseña1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambiarContraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCambiarContraseñaConfirmar;
    public javax.swing.JCheckBox jCheckBoxCambiarContraseña1;
    public javax.swing.JCheckBox jCheckBoxCambiarContraseña2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator7;
    public javax.swing.JTextField jTextCambiarContraseñaConfirmar1;
    public javax.swing.JTextField jTextCambiarContraseñaConfirmar2;
    public javax.swing.JLabel lbRegistrar;
    // End of variables declaration//GEN-END:variables
}
