/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author MIGUEL TULANDE
 */
public class ComprobarPreguntaSeguridad extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public ComprobarPreguntaSeguridad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbInicioSesion = new javax.swing.JLabel();
        btnComprobarPreguntasSeguridadConfirmar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jTextComprobarPreguntasSeguridadSu_pregunta_es = new javax.swing.JTextField();
        jTextComprobarPreguntaSeguridadEscribasuRespuesta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbInicioSesion.setBackground(new java.awt.Color(0, 0, 0));
        lbInicioSesion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbInicioSesion.setForeground(new java.awt.Color(0, 0, 0));
        lbInicioSesion.setText("RECUPERAR CUENTA");
        jPanel1.add(lbInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        btnComprobarPreguntasSeguridadConfirmar.setBackground(new java.awt.Color(0, 153, 255));
        btnComprobarPreguntasSeguridadConfirmar.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        btnComprobarPreguntasSeguridadConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnComprobarPreguntasSeguridadConfirmar.setText("CONFIRMAR");
        btnComprobarPreguntasSeguridadConfirmar.setBorder(null);
        jPanel1.add(btnComprobarPreguntasSeguridadConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 170, 30));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 290, 470));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, -1, 360));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 360, 10));

        jTextComprobarPreguntasSeguridadSu_pregunta_es.setBackground(new java.awt.Color(204, 204, 204));
        jTextComprobarPreguntasSeguridadSu_pregunta_es.setForeground(new java.awt.Color(0, 0, 0));
        jTextComprobarPreguntasSeguridadSu_pregunta_es.setText("Su pregunat es:");
        jTextComprobarPreguntasSeguridadSu_pregunta_es.setBorder(null);
        jTextComprobarPreguntasSeguridadSu_pregunta_es.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextComprobarPreguntasSeguridadSu_pregunta_esActionPerformed(evt);
            }
        });
        jPanel1.add(jTextComprobarPreguntasSeguridadSu_pregunta_es, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 360, 30));

        jTextComprobarPreguntaSeguridadEscribasuRespuesta.setBackground(new java.awt.Color(204, 204, 204));
        jTextComprobarPreguntaSeguridadEscribasuRespuesta.setForeground(new java.awt.Color(0, 0, 0));
        jTextComprobarPreguntaSeguridadEscribasuRespuesta.setText("Escriba su respuesta");
        jTextComprobarPreguntaSeguridadEscribasuRespuesta.setBorder(null);
        jTextComprobarPreguntaSeguridadEscribasuRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextComprobarPreguntaSeguridadEscribasuRespuestaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextComprobarPreguntaSeguridadEscribasuRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 360, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextComprobarPreguntasSeguridadSu_pregunta_esActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextComprobarPreguntasSeguridadSu_pregunta_esActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextComprobarPreguntasSeguridadSu_pregunta_esActionPerformed

    private void jTextComprobarPreguntaSeguridadEscribasuRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextComprobarPreguntaSeguridadEscribasuRespuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextComprobarPreguntaSeguridadEscribasuRespuestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprobarPreguntaSeguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprobarPreguntaSeguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprobarPreguntaSeguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprobarPreguntaSeguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComprobarPreguntaSeguridad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnComprobarPreguntasSeguridadConfirmar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator8;
    public javax.swing.JTextField jTextComprobarPreguntaSeguridadEscribasuRespuesta;
    public javax.swing.JTextField jTextComprobarPreguntasSeguridadSu_pregunta_es;
    private javax.swing.JLabel lbInicioSesion;
    // End of variables declaration//GEN-END:variables
}
