/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author MIGUEL TULANDE
 */
public class PreguntaSeguridad_1 extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public PreguntaSeguridad_1() {
        initComponents();
    }

    /**
     * This method is called from within the
     * constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbInicioSesion = new javax.swing.JLabel();
        btnPreguntaSeguridadConfirmar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jTextPreguntaSeguridadSelecioneTIpo = new javax.swing.JTextField();
        jComboBoxPreguntaSeguridadTipoPregunta = new javax.swing.JComboBox<>();
        jSeparator8 = new javax.swing.JSeparator();
        jTextPreguntaSeguridadEscribaRespuesta = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jTextPreguntaSeguridadEscribaRespuestaConfirmar = new javax.swing.JTextField();
        lbPreguntaSeguridadSeleccioneTipoPregunta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbInicioSesion.setBackground(new java.awt.Color(0, 0, 0));
        lbInicioSesion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbInicioSesion.setForeground(new java.awt.Color(0, 0, 0));
        lbInicioSesion.setText("PREGUNTA DE RECUPERACIÓN");
        jPanel1.add(lbInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        btnPreguntaSeguridadConfirmar.setBackground(new java.awt.Color(0, 153, 255));
        btnPreguntaSeguridadConfirmar.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        btnPreguntaSeguridadConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnPreguntaSeguridadConfirmar.setText("CONFIRMAR");
        btnPreguntaSeguridadConfirmar.setBorder(null);
        jPanel1.add(btnPreguntaSeguridadConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 170, 30));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 290, 470));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, -1, 360));

        jTextPreguntaSeguridadSelecioneTIpo.setBackground(new java.awt.Color(204, 204, 204));
        jTextPreguntaSeguridadSelecioneTIpo.setForeground(new java.awt.Color(0, 0, 0));
        jTextPreguntaSeguridadSelecioneTIpo.setBorder(null);
        jTextPreguntaSeguridadSelecioneTIpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPreguntaSeguridadSelecioneTIpoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextPreguntaSeguridadSelecioneTIpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, 30));

        jComboBoxPreguntaSeguridadTipoPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPreguntaSeguridadTipoPreguntaActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxPreguntaSeguridadTipoPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 380, 20));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 360, 10));

        jTextPreguntaSeguridadEscribaRespuesta.setBackground(new java.awt.Color(204, 204, 204));
        jTextPreguntaSeguridadEscribaRespuesta.setForeground(new java.awt.Color(0, 0, 0));
        jTextPreguntaSeguridadEscribaRespuesta.setText("Escriba su respuesta");
        jTextPreguntaSeguridadEscribaRespuesta.setBorder(null);
        jTextPreguntaSeguridadEscribaRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPreguntaSeguridadEscribaRespuestaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextPreguntaSeguridadEscribaRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 270, 30));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 360, 10));

        jTextPreguntaSeguridadEscribaRespuestaConfirmar.setBackground(new java.awt.Color(204, 204, 204));
        jTextPreguntaSeguridadEscribaRespuestaConfirmar.setForeground(new java.awt.Color(0, 0, 0));
        jTextPreguntaSeguridadEscribaRespuestaConfirmar.setText("Escriba su respuesta otra vez");
        jTextPreguntaSeguridadEscribaRespuestaConfirmar.setBorder(null);
        jTextPreguntaSeguridadEscribaRespuestaConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPreguntaSeguridadEscribaRespuestaConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(jTextPreguntaSeguridadEscribaRespuestaConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 270, 30));

        lbPreguntaSeguridadSeleccioneTipoPregunta.setForeground(new java.awt.Color(0, 0, 0));
        lbPreguntaSeguridadSeleccioneTipoPregunta.setText("Selecione el tipo de pregunta de recuperacion que va tener su cuenta");
        jPanel1.add(lbPreguntaSeguridadSeleccioneTipoPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 380, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPreguntaSeguridadSelecioneTIpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPreguntaSeguridadSelecioneTIpoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPreguntaSeguridadSelecioneTIpoActionPerformed

    private void jComboBoxPreguntaSeguridadTipoPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPreguntaSeguridadTipoPreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPreguntaSeguridadTipoPreguntaActionPerformed

    private void jTextPreguntaSeguridadEscribaRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPreguntaSeguridadEscribaRespuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPreguntaSeguridadEscribaRespuestaActionPerformed

    private void jTextPreguntaSeguridadEscribaRespuestaConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPreguntaSeguridadEscribaRespuestaConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPreguntaSeguridadEscribaRespuestaConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreguntaSeguridad_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnPreguntaSeguridadConfirmar;
    public javax.swing.JComboBox<String> jComboBoxPreguntaSeguridadTipoPregunta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JTextField jTextPreguntaSeguridadEscribaRespuesta;
    public javax.swing.JTextField jTextPreguntaSeguridadEscribaRespuestaConfirmar;
    public javax.swing.JTextField jTextPreguntaSeguridadSelecioneTIpo;
    private javax.swing.JLabel lbInicioSesion;
    public javax.swing.JLabel lbPreguntaSeguridadSeleccioneTipoPregunta;
    // End of variables declaration//GEN-END:variables
}
